### ISSUE TITLE
build-indices error

### ISSUE THREAD

**Issue by HollyRuess** [jeffhussmann/knock-knock#2]
I've install knock-knock in a conda environment with python=3.6. During the testing on example_data, I received an error during the build-indices step.

$ knock-knock build-indices project_folder hg38

"Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly"

**Comment by jeffhussmann** [comment]
Hi Holly - 

As a temporary fix, it looks like downgrading to a version of Biopython <1.78 should prevent this error - https://biopython.org/wiki/Alphabet.

 - Jeff

**Comment by HollyRuess** [comment]
Hi Jeff,

It appears that my bioconda is already 1.78. I already tried downgrading it to 1.70 but I run into multiple conflicts with conda-forge. 

Here's a list and version of the packages in my environment.
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
argon2-cffi               20.1.0           py36h8f6f2f9_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
biopython                 1.78             py36h8f6f2f9_1    conda-forge
blast                     2.7.1                h4422958_6    bioconda
bleach                    3.3.0              pyh44b312d_0    conda-forge
bokeh                     2.2.3            py36h5fab9bb_0    conda-forge
boost                     1.67.0           py36h3e44d54_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py36h5fab9bb_1    conda-forge
cffi                      1.14.4           py36hc120d54_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.5.19               h2a4e5f8_1    conda-forge
hits                      0.1              py36h4c5857e_1    bioconda
htslib                    1.11                 hd3b49d5_1    bioconda
icu                       58.2              hf484d3e_1000    conda-forge
importlib-metadata        3.4.0            py36h5fab9bb_0    conda-forge
importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
ipykernel                 5.4.2            py36he448a4c_0    conda-forge
ipython                   7.16.1           py36he448a4c_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jedi                      0.17.2           py36h5fab9bb_1    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.1            py36h5fab9bb_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
kiwisolver                1.3.1            py36h605e78d_1    conda-forge
knock-knock               0.2.1                      py_0    bioconda
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libwebp-base              1.2.0                h7f98852_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markupsafe                1.1.1            py36h8f6f2f9_3    conda-forge
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py36he12231b_1    conda-forge
minimap2                  2.16                 h84994c4_1    bioconda
mistune                   0.8.4           py36h8f6f2f9_1003    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py36h5fab9bb_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
nettle                    3.3                           0    conda-forge
notebook                  6.2.0            py36h5fab9bb_0    conda-forge
numpy                     1.19.5           py36h2aa4a07_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.1.5            py36h284efc9_0    conda-forge
pandoc                    2.11.4               h7f98852_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parallel                  20201122             ha770c72_0    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-archive-tar          2.32                    pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py36ha6010c0_2    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.14             pyha770c72_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py36h8f6f2f9_2    conda-forge
pysam                     0.16.0.1         py36h4c34d4e_1    bioconda
python                    3.6.12          hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py36h8f6f2f9_0    conda-forge
pyzmq                     22.0.1           py36h81c33ee_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
samtools                  1.11                 h6270b1f_0    bioconda
scipy                     1.5.3            py36h9e8f40b_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py36h5fab9bb_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
star                      2.7.7a                        0    bioconda
terminado                 0.9.2            py36h5fab9bb_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tornado                   6.1              py36h8f6f2f9_1    conda-forge
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py36h5fab9bb_4    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge

**Comment by HollyRuess** [comment]
Jeff,

I should have read your note better. I was able to downgrade to biopython=1.77 and it seems to be working.

Holly

**Comment by HollyRuess** [comment]
Jeff,

I'm still trying to run the test data, however, I still get lots of errors and can't seem to get past them. Please let me know if you are using conda or pip for your installation. Plus, let me know the exact versions in the environments. I'm assuming that I will need to downgrade more packages (for instance matplotlib <3.3).

Here's what I tried and the errors:
1)
$ knock-knock parallel example_data 2
/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/experiment.py:2: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('Agg', warn=False)
/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/visualize.py:9: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('Agg', warn=False)
/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/svg.py:8: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('Agg', warn=False)
Traceback (most recent call last):
  File "/home/.conda/envs/knock-knock/bin/knock-knock", line 285, in <module>
    args.func(args)
  File "/home/.conda/envs/knock-knock/bin/knock-knock", line 59, in parallel
    exps = experiment.get_all_experiments(args.project_directory, args.conditions)
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/experiment.py", line 1942, in get_all_experiments
    exp = exp_class(base_dir, group, name, description=description, progress=progress)
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/experiment.py", line 1221, in __init__
    auto_length = int((self.target_info.amplicon_length * 2.5 // 1000 + 1)) * 1000
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/hits/utilities.py", line 171, in memoized_f
    setattr(self, attr_name, f(self))
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/experiment.py", line 150, in target_info
    supplemental_headers=self.supplemental_headers,
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/hits/utilities.py", line 171, in memoized_f
    setattr(self, attr_name, f(self))
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/experiment.py", line 140, in supplemental_headers
    return {name: sam.header_from_STAR_index(d['STAR']) for name, d in self.supplemental_indices.items()}
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/hits/utilities.py", line 171, in memoized_f
    setattr(self, attr_name, f(self))
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/experiment.py", line 136, in supplemental_indices
    return {name: locations[name] for name in self.supplemental_index_names}
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/experiment.py", line 136, in <dictcomp>
    return {name: locations[name] for name in self.supplemental_index_names}
KeyError: 'e_coli'


2)
$ knock-knock process example_data illumina B_ULT
/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/experiment.py:2: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('Agg', warn=False)
/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/visualize.py:9: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('Agg', warn=False)
/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/svg.py:8: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('Agg', warn=False)
Traceback (most recent call last):
  File "/home/.conda/envs/knock-knock/bin/knock-knock", line 285, in <module>
    args.func(args)
  File "/home/.conda/envs/knock-knock/bin/knock-knock", line 111, in process
    exp.process(stage)
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/experiment.py", line 1665, in process
    self.generate_alignments(read_type)
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/experiment.py", line 319, in generate_alignments
    blast.blast(self.target_info.fns['ref_fasta'],
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/hits/utilities.py", line 171, in memoized_f
    setattr(self, attr_name, f(self))
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/experiment.py", line 151, in target_info
    infer_homology_arms=self.infer_homology_arms,
  File "/home/.conda/envs/knock-knock/lib/python3.6/site-packages/knock_knock/target_info.py", line 45, in __init__
    manifest = yaml.safe_load(manifest_fn.open())
  File "/home/.conda/envs/knock-knock/lib/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/home/.conda/envs/knock-knock/lib/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/home/.conda/envs/knock-knock/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'test_data/targets/BCAP31_GFP11_U_ILL/manifest.yaml'


Holly

**Comment by HollyRuess** [comment]
I've managed to get the software installed and was able to run through the Illumina data. I had to downgrade a few packages and changes to mappingtools.py (replace LoadAndKeep with NoSharedMemory)

Here's the list of packages and versions in my conda environment (in case anyone else needs to troubleshoot the install)
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
argon2-cffi               20.1.0           py36h8f6f2f9_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
biopython                 1.77             py36h8c4c3a4_1    conda-forge
blast                     2.7.1                h4422958_6    bioconda
bleach                    3.3.0              pyh44b312d_0    conda-forge
bokeh                     2.2.3            py36h5fab9bb_0    conda-forge
boost                     1.67.0           py36h3e44d54_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py36h5fab9bb_1    conda-forge
cffi                      1.14.4           py36hc120d54_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.5.19               h2a4e5f8_1    conda-forge
hits                      0.1              py36h4c5857e_1    bioconda
htslib                    1.11                 hd3b49d5_1    bioconda
icu                       58.2              hf484d3e_1000    conda-forge
importlib-metadata        3.4.0            py36h5fab9bb_0    conda-forge
importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
ipykernel                 5.4.2            py36he448a4c_0    conda-forge
ipython                   7.16.1           py36he448a4c_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jedi                      0.17.2           py36h5fab9bb_1    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.1            py36h5fab9bb_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
kiwisolver                1.3.1            py36h605e78d_1    conda-forge
knock-knock               0.2.1                      py_0    bioconda
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libwebp-base              1.2.0                h7f98852_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markupsafe                1.1.1            py36h8f6f2f9_3    conda-forge
matplotlib                3.2.2                         1    conda-forge
matplotlib-base           3.2.2            py36hef1b27d_0  
minimap2                  2.16                 h84994c4_1    bioconda
mistune                   0.8.4           py36h8f6f2f9_1003    conda-forge
nbconvert                 5.6.1            py36h9f0ad1d_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
nettle                    3.3                           0    conda-forge
notebook                  6.2.0            py36h5fab9bb_0    conda-forge
numpy                     1.19.5           py36h2aa4a07_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.1.5            py36h284efc9_0    conda-forge
pandoc                    2.11.4               h7f98852_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parallel                  20201122             ha770c72_0    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-archive-tar          2.32                    pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py36ha6010c0_2    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.14             pyha770c72_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py36h8f6f2f9_2    conda-forge
pysam                     0.16.0.1         py36h4c34d4e_1    bioconda
python                    3.6.12          hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py36h8f6f2f9_0    conda-forge
pyzmq                     22.0.1           py36h81c33ee_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
samtools                  1.11                 h6270b1f_0    bioconda
scipy                     1.5.3            py36h9e8f40b_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py36h5fab9bb_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
star                      2.7.7a                        0    bioconda
terminado                 0.9.2            py36h5fab9bb_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tornado                   6.1              py36h8f6f2f9_1    conda-forge
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py36h5fab9bb_4    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge
