### ISSUE TITLE
build-targets step error

### ISSUE THREAD

**Issue by shp9n** [jeffhussmann/knock-knock#5]
I hope to use knock-knock to analyze diverse insertion events by sgRNA/Cas9 and homology donor, but got the below message at the build-targets step. I wonder if the current version of the script is compatible with the example files from 3 years ago or if I missed something from setup. 
Any guidance would be greatly appreciated. Thank you very much for your time!

knock-knock build-targets PROJECT_DIR

Traceback (most recent call last):
  File "/opt/rice/anaconda3/bin/knock-knock", line 236, in <module>
    args.func(args)
  File "/opt/rice/anaconda3/bin/knock-knock", line 124, in build_targets
    defer_HA_identification=args.defer_HA_identification,
  File "/opt/rice/anaconda3/lib/python3.7/site-packages/knock_knock/build_targets.py", line 1142, in build_target_infos_from_csv
    for pegRNA_name, pegRNA_components in info['pegRNAs']:
TypeError: 'NoneType' object is not iterable

**Comment by hukai916** [comment]
I am also testing out knock-knock, the example files seem still work.

**Comment by shp9n** [comment]
Thank you!

**Comment by hukai916** [comment]
Hi @shp9n ,

Also checkout: https://github.com/jeffhussmann/knock-knock/issues/12

**Comment by shp9n** [comment]
Hi @hukai916,
I checked #12 on v0.4.1.
Were you able to run the example file using Version 0.3.7 using the donor sequence?
Thanks!

**Comment by hukai916** [comment]
@shp9n , nope, `knock-knock` can not properly read in the donor sequence in my test. It could be due to outdated example column name, but I am not sure. When I have time, I can dig into it further.

**Comment by jeffhussmann** [comment]
Hi @shp9n -

Thanks for you interest in knock-knock!

The issues you have run in to should be fixed by commit https://github.com/jeffhussmann/knock-knock/commit/1871c414a7090f2d3f0ee52648377f1da4b39c5e. See also discussion in https://github.com/jeffhussmann/knock-knock/issues/12.
