### ISSUE TITLE
Can't install knock-knock via conda

### ISSUE THREAD

**Issue by hukai916** [jeffhussmann/knock-knock#6]
Hi developers,

Thanks for creating knock-knock! I am interested to test it out, however, the current conda version is still at 0.2.1, far behind the current pip version 0.3.8, is there a plan to update the conda platform?

Moreover, the conda install takes forever to install, I have tried to install via conda the whole morning and got no luck, it kept hanging at the `Solving environment:` step, and sometimes pop out message like `The following specifications were found to be incompatible with each other:` and stops.

If I use pip to install the latest 0.3.8, is there any version requirement for other dependencies like STAR, minimap2?

Any input will be appreciated!

--Kai

**Comment by jeffhussmann** [comment]
Hi Kai - 

Thanks for your interest.

There is a general goal to have the conda version more closely track the latest version on github. As you have noticed, however, solving the conda enviroment frequently takes prohibitively long or fails entirely, and I do not have the conda expertise or patience to figure out why. If you have any insight, it would be much appreciated!

In general, my experience has been that knock-knock is able to handle a range of versions for blastn, minimap2, and STAR, but I can't rule out that particular versions of these may change behavior that knock-knock is dependent on. FWIW, the versions currently installed on my machine are

```
$ blastn -version
blastn: 2.13.0+
 Package: blast 2.13.0, build Jul 18 2022 22:49:37

$ STAR --version
2.7.10a_alpha_220818

$ minimap2 --version
2.24-r1122
```

 - Jeff

**Comment by hukai916** [comment]
Thanks Jeff, I can install knock-knock via pip. I may come up with more questions as I test knock-knock with your in-house data. BTW, I recommend creating a docker/singularity image to ease the burden of installations for users. I have created one which can be pulled by: `docker pull hukai916/knock-knock:0.1`, which contains 0.3.8 and all dependencies. Best,
