### ISSUE TITLE
The hits library?

### ISSUE THREAD

**Issue by hukai916** [jeffhussmann/knock-knock#7]
Hi developers,

Can you provide more information on the `hits` library mentioned here: 
https://github.com/jeffhussmann/knock-knock/blob/db69b183f910a11a7e38b45d4814a19a536b63c1/knock_knock/build_targets.py#L23

Thanks,

**Comment by jeffhussmann** [comment]
The `hits`  library is `https://github.com/jeffhussmann/hits`, a collection of general purpose utilities for processing sequencing data.

The most up-to-date version of `knock-knock` will generally require the most up-to-date version of `hits` - unfortunately, I have not done a good job of tracking the exact historical relationship between versions of the two.
