### ISSUE TITLE
max_relevant_length?

### ISSUE THREAD

**Issue by hukai916** [jeffhussmann/knock-knock#8]
Hi Jeff,

Seems that the `max_relevant_length` column in pacbio sample sheet is not defined. Does it refer to the maximum read length of my fastq file? Can I set an arbitrarily large number for my samples since I have many to run or I must set the exact max read length for each sample?

Thanks, 

--Kai

**Comment by jeffhussmann** [comment]
Hi Kai - 

`max_relevant_length` is only used to set the x-axis limits in amplicon length distribution plots. If you don't use these plots, it does not need to be set at all. If you do, set it to a value that you expect to contain the majority of the length range you are interested in.
