### ISSUE TITLE
Missing 1 required positional argument: `stages`

### ISSUE THREAD

**Issue by hukai916** [jeffhussmann/knock-knock#9]
Hi Jeff,

When running the `knock-knock process` command, I encountered the following error:
```
Traceback (most recent call last):
  File "/opt/conda/bin/knock-knock", line 236, in <module>
    args.func(args)
TypeError: process() missing 1 required positional argument: 'stages'
```

Also, in your example, it says:
```
knock-knock process PROJECT_DIR EXAMPLE_GROUP EXAMPLE_SAMPLE
```
What does `EXAMPLE_SAMPLE` mean? Can you provide some concrete example?

Thanks and best, 

--Kai

**Comment by jeffhussmann** [comment]
Consolidating discussion in https://github.com/jeffhussmann/knock-knock/issues/12.
